### ISSUE TITLE
Using Java 8 and Spigot 1.8.9

### ISSUE THREAD

**Issue by TheIntelloBox** [MysticCity/MinigamesAPI#100]
[14:52:44] [Server thread/WARN]: [ServerSigns] Error while executing task PlayerTask{data='oitc join Map1'} de.czymm.serversigns.taskmanager.tasks.PlayerActionTask@24d208d9
org.bukkit.command.CommandException: Unhandled exception executing command 'oitc' in plugin MGOITC v1.14.10-20160814.071553
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:242) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at de.czymm.serversigns.taskmanager.tasks.PlayerActionTask.performCommand(PlayerActionTask.java:22) ~[ServerSigns%20(2).jar:?]
at de.czymm.serversigns.taskmanager.tasks.PlayerActionTask.runPlayerTask(PlayerActionTask.java:51) ~[ServerSigns%20(2).jar:?]
at de.czymm.serversigns.taskmanager.tasks.PlayerTask.runTask(PlayerTask.java:34) ~[ServerSigns%20(2).jar:?]
at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTaskImpl(TaskManagerTaskExecutor.java:45) [ServerSigns%20(2).jar:?]
at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTask(TaskManagerTaskExecutor.java:38) [ServerSigns%20(2).jar:?]
at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTask(TaskManagerTaskExecutor.java:14) [ServerSigns%20(2).jar:?]
at de.czymm.serversigns.taskmanager.TaskManager.addTask(TaskManager.java:91) [ServerSigns%20(2).jar:?]
at de.czymm.serversigns.signs.ServerSignExecutor.executeSignFull(ServerSignExecutor.java:103) [ServerSigns%20(2).jar:?]
at de.czymm.serversigns.listeners.PlayerListener.playerInteractCheck(PlayerListener.java:60) [ServerSigns%20(2).jar:?]
at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
at com.comze_instancelabs.minigamesapi.MinigamesAPI.uuidToPlayer(MinigamesAPI.java:1305) ~[?:?]
at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:759) ~[?:?]
at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:743) ~[?:?]
at com.comze_instancelabs.minigamesapi.commands.CommandHandler.joinArena(CommandHandler.java:658) ~[?:?]
at com.comze_instancelabs.minigamesapi.commands.CommandHandler.handleArgs(CommandHandler.java:116) ~[?:?]
at com.comze_instancelabs.oitc.Main.onCommand(Main.java:115) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
... 33 more

**Comment by mepeisen** [comment]
thx. I was able to reproduce it. Actually the original problem is that it could not detect 1.8.8/1.8.9 as server version. Do not know why I forget this version.
However I will fix it in the next hours.

**Comment by mepeisen** [comment]
please retry with latest snapshot: http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.11-SNAPSHOT/Minigames-All-1.14.11-20160817.071937-5-bin.zip

**Comment by mepeisen** [comment]
closing this issue.
If there are still problems please write a new comment.
