### ISSUE TITLE
Lib-Exception

### ISSUE THREAD

**Issue by mepeisen** [MysticCity/MinigamesAPI#112]
[17:20:58 WARN]: [MinigamesLib] Failed sending title packet
java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.ChatSerializer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:260) ~[?:1.8.0_25]
	at com.comze_instancelabs.minigamesapi.Effects.playTitle(Effects.java:248) [MinigamesLib.jar:?]
	at com.comze_instancelabs.minigamesapi.Rewards.giveWinReward(Rewards.java:358) [MinigamesLib.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.lambda$9(Arena.java:1292) [MinigamesLib.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena$$Lambda$24/1353840551.run(Unknown Source) [MinigamesLib.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10-R0.1-SNAPSHOT.jar:git-Spigot-c55900f-9af379f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by mepeisen** [comment]
fixed
