### ISSUE TITLE
Bug MgSplegg using Spigot 1.8.9 and Java 8.

### ISSUE THREAD

**Issue by TheIntelloBox** [MysticCity/MinigamesAPI#154]
[19:51:36] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MGSplegg v1.14.12-20160825.211219
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:717) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at com.comze_instancelabs.minigamesapi.util.IconMenu.open(IconMenu.java:94) ~[?:?]
	at com.comze_instancelabs.minigamesapi.SpectatorManager.openSpectatorGUI(SpectatorManager.java:148) ~[?:?]
	at com.comze_instancelabs.minigamesapi.ArenaListener.onSignUse(ArenaListener.java:1655) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor313.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	... 18 more
[19:51:37] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MGSplegg v1.14.12-20160825.211219
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:717) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at com.comze_instancelabs.minigamesapi.util.IconMenu.open(IconMenu.java:94) ~[?:?]
	at com.comze_instancelabs.minigamesapi.SpectatorManager.openSpectatorGUI(SpectatorManager.java:148) ~[?:?]
	at com.comze_instancelabs.minigamesapi.ArenaListener.onSignUse(ArenaListener.java:1655) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor313.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	... 18 more

**Comment by mepeisen** [comment]
this happens every time a player is in spectator mode and tries to open the gui?

**Comment by TheIntelloBox** [comment]
Yes of course.
And we can't leave the game, can't place bloc, and can't break bloc. This is the same thing when we are op.

**Comment by mepeisen** [comment]
Are there other exceptions or Problems? Can you send me a complete log to mep_eisen@web.de from server start to the problems and exceptions?

**Comment by TheIntelloBox** [comment]
Any other problem.

**Comment by mepeisen** [comment]
Can you provide a complete log file?

**Comment by TheIntelloBox** [comment]
No I can't. ;(

**Comment by mepeisen** [comment]
I will try to reproduce it this weekend

**Comment by TheIntelloBox** [comment]
Okay ! :)

**Comment by mepeisen** [comment]
Please retry with latest snapshot.
Download links: https://github.com/MysticCity/MinigamesAPI/wiki/Installation

If you get additional exceptions please reopen the issue.

**Comment by TheIntelloBox** [comment]
Please post it on Spigot because Norton said me that this is a virus.

**Comment by mepeisen** [comment]
Hmm. Avira does not find any virus. Then you will have to wait for the next release.

**Comment by TheIntelloBox** [comment]
Ok and when it is ?

**Comment by mepeisen** [comment]
in the next 7 days.

**Comment by TheIntelloBox** [comment]
Okay fine !

**Comment by TheIntelloBox** [comment]
When is the update now ?

**Comment by mepeisen** [comment]
should be today

**Comment by TheIntelloBox** [comment]
Okay.

**Comment by mepeisen** [comment]
sry for the delay. There were some ciritcal issues at work so that I had to spent several days without having time for my hobby :-(
The new version should be ready this saturday. Only two open bugs.

**Comment by TheIntelloBox** [comment]
Okay, fine, no problem ! :D

**Comment by TheIntelloBox** [comment]
When it is now ?

**Comment by MysticCity** [comment]
PLS wait a bit.
We have an RealLife and this Projekts are Free.
If you want faster Support/Releases give us so much money that we can code 24/7.

**Comment by TheIntelloBox** [comment]
And now ? :(

**Comment by mepeisen** [comment]
sry, I did have some kind of chaos at work. This weekend it will be published.

**Comment by TheIntelloBox** [comment]
Now ? :(

**Comment by mepeisen** [comment]
https://github.com/MCE-Plugins/MInigames-All/releases/tag/v1.14.13
Sry for the delay.
