### ISSUE TITLE
SkyWars Scoreboard

### ISSUE THREAD

**Issue by BBoyJD10** [MysticCity/MinigamesAPI#163]
Hi i have an issue with SkyWars. It doesnt seem to update the scoreboard with the custom one. no matter what i put it keeps the same old one. Using latest version! Please help

**Comment by BBoyJD10** [comment]
Error: 16.09 15:35:24 [Server] ERROR Failed to set custom scoreboard
16.09 15:35:24 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 1
16.09 15:35:24 [Server] INFO at com.comze_instancelabs.minigamesapi.util.ArenaScoreboard.lambda$updateScoreboard$48(ArenaScoreboard.java:131) ~[?:?]
16.09 15:35:24 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-f9671b8-48b88ed]
16.09 15:35:24 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-f9671b8-48b88ed]
16.09 15:35:24 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot.jar:git-Spigot-f9671b8-48b88ed]
16.09 15:35:24 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-f9671b8-48b88ed]
16.09 15:35:24 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-f9671b8-48b88ed]
16.09 15:35:24 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-f9671b8-48b88ed]

**Comment by BBoyJD10** [comment]
Config: 

  custom_scoreboard:
    line0: ' '
    line1: '&a&lWelcome :'
    line2: '<player>'
    line3: ' '
    line4: '&a&lGame Stats :'
    line5: '&bGame: &dSkyWars'
    line6: '&bMap: &d<arena>'
    line7: '&bPlayers: &d<playeralivecount>'
    line8: '&bSpectators: &d<lostplayercount>'

**Comment by HyperBlueCore** [comment]
maybe it is caused by the empty lines or line 0

**Comment by BBoyJD10** [comment]
How can i do blank lines on scoreboard?

**Comment by mepeisen** [comment]
Please change the config.
At the moment the following syntax is required:

custom_scoreboard:
    line0: '0: '
    line1: '1:&a&lWelcome :'
    line2: '2:<player>'
    line3: '3: '
    line4: '4:&a&lGame Stats :'
    line5: '5:&bGame: &dSkyWars'
    line6: '6:&bMap: &d<arena>'
    line7: '7:&bPlayers: &d<playeralivecount>'
    line8: '8:&bSpectators: &d<lostplayercount>'

**Comment by BBoyJD10** [comment]
That caused this to happen:

https://gyazo.com/9b8e39ba8082c70d8e44649bb83da7ab

**Comment by mepeisen** [comment]
You can try to experiment but at the moment each line requires at least one colon.
moved to version 2.

**Comment by BBoyJD10** [comment]
Please allow for blank lines!

**Comment by BBoyJD10** [comment]
Please allow for the blank lines very important :)
