### ISSUE TITLE
Bugs using Spigot 1.11 and Java 8.

### ISSUE THREAD

**Issue by TheIntelloBox** [MysticCity/MinigamesAPI#176]
Hello,

I have this error : 
[11:07:02] [Server thread/ERROR]: [MinigamesLib] Problems converting player to uuid.
java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.EntityPlayer.getUniqueID()
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_72]
	at com.comze_instancelabs.minigamesapi.MinigamesAPI.playerToUUID(MinigamesAPI.java:1367) [MinigamesLib-1.14.13.jar:?]
	at com.comze_instancelabs.minigamesapi.MinigamesAPI.uuidToPlayer(MinigamesAPI.java:1393) [MinigamesLib-1.14.13.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:759) [MinigamesLib-1.14.13.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:743) [MinigamesLib-1.14.13.jar:?]
	at com.comze_instancelabs.minigamesapi.ArenaListener.onSignUse(ArenaListener.java:1505) [MinigamesLib-1.14.13.jar:?]
	at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[11:07:02] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MGOITC v1.14.12-20160825.211106
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at com.comze_instancelabs.minigamesapi.MinigamesAPI.uuidToPlayer(MinigamesAPI.java:1393) ~[?:?]
	at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:759) ~[?:?]
	at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:743) ~[?:?]
	at com.comze_instancelabs.minigamesapi.ArenaListener.onSignUse(ArenaListener.java:1505) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	... 17 more

Thanks for fixing it.

**Comment by mepeisen** [comment]
Any error before? There should be a log entry, saying "Loaded MinigamesAPI. We're on "
What Version does it say?

Also the line numbers are incorrect. 1.11 is not yet released and seems you are using an incompatible Version.
For testing 1.11 Support please use the latest snapshot at http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.14-SNAPSHOT/
(the one from 24th of November)

**Comment by mepeisen** [comment]
closed because of no response

**Comment by TheIntelloBox** [comment]
It works fine. :D

**Comment by mepeisen** [comment]
thx :-)
