### ISSUE TITLE
Problems converting player to uuid.

### ISSUE THREAD

**Issue by tjeard** [MysticCity/MinigamesAPI#179]
`[13:30:08 ERROR]: [MinigamesLib] Problems converting player to uuid.
java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.EntityPlayer.getUniqueID()
        at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_111]
        at com.comze_instancelabs.minigamesapi.MinigamesAPI.playerToUUID(MinigamesAPI.java:1367) [MinigamesLib-1.14.13.jar:?]
        at com.comze_instancelabs.minigamesapi.MinigamesAPI.uuidToPlayer(MinigamesAPI.java:1393) [MinigamesLib-1.14.13.jar:?]
        at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:759) [MinigamesLib-1.14.13.jar:?]
        at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:743) [MinigamesLib-1.14.13.jar:?]
        at com.comze_instancelabs.gungame.IArena.joinPlayerLobby(IArena.java:48) [MGGunGame-Plugin-1.14.13.jar:?]
        at com.comze_instancelabs.minigamesapi.commands.CommandHandler.joinArena(CommandHandler.java:668) [MinigamesLib-1.14.13.jar:?]
        at com.comze_instancelabs.minigamesapi.commands.CommandHandler.handleArgs(CommandHandler.java:125) [MinigamesLib-1.14.13.jar:?]
        at com.comze_instancelabs.gungame.Main.onCommand(Main.java:173) [MGGunGame-Plugin-1.14.13.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[13:30:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gg' in plugin MGGungame v1.14.13-20161112.134739
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-7d78b81-13a5b12]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-7d78b81-13a5b12]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-13a5b12]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.comze_instancelabs.minigamesapi.MinigamesAPI.uuidToPlayer(MinigamesAPI.java:1393) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:759) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Arena.joinPlayerLobby(Arena.java:743) ~[?:?]
        at com.comze_instancelabs.gungame.IArena.joinPlayerLobby(IArena.java:48) ~[?:?]
        at com.comze_instancelabs.minigamesapi.commands.CommandHandler.joinArena(CommandHandler.java:668) ~[?:?]
        at com.comze_instancelabs.minigamesapi.commands.CommandHandler.handleArgs(CommandHandler.java:125) ~[?:?]
        at com.comze_instancelabs.gungame.Main.onCommand(Main.java:173) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-7d78b81-13a5b12]
        ... 15 more
`

**Comment by mepeisen** [comment]
For spigot 1.11 please use the 1.14.14 snapshot. http://www.minigameslib.de/downloads_en.php
