### ISSUE TITLE
Bedwars: NPC not showing items

### ISSUE THREAD

**Issue by LittlePapaJohn** [MysticCity/MinigamesAPI#182]
Using latest version 1.14.14  build 10 in 1.11 and 1.11.2 on Spigot and the NPCs in bedwars show the main menus for items like blocks but when I click on blocks he does give me anything to buy. I use the default gui for the items. Additional plugins: build 725 multiverse-core and current version Vault and worldedit.

**Comment by LittlePapaJohn** [comment]
Added the error message related to it:
[20:36:56 INFO]: [MinigamesLib] Arena LPJG_BedWars started because of start command from player LittlePapaJohn
[20:37:06 WARN]: [MGBedWars] [arena:LPJG_BedWars] Failed to set class
java.lang.NullPointerException
        at com.comze_instancelabs.minigamesapi.Classes.getClass(Classes.java:144) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Arena.startRaw(Arena.java:1743) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Arena.lambda$start$20(Arena.java:1701) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
[20:37:13 WARN]: [MGBedWars] Task #69 for MGBedWars v1.14.14-20161219.093749 generated an exception
java.lang.NullPointerException
        at net.minecraft.server.v1_11_R1.MerchantRecipeList.a(SourceFile:83) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.EntityPlayer.openTrade(EntityPlayer.java:768) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at com.comze_instancelabs.bedwars.villager.NMSMerchant111.openTrading(NMSMerchant111.java:52) ~[?:?]
        at com.comze_instancelabs.bedwars.villager.Merchant111.openTrading(Merchant111.java:62) ~[?:?]
        at com.comze_instancelabs.bedwars.gui.MainGUI$3.run(MainGUI.java:106) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]

**Comment by mepeisen** [comment]
fixed in 1.14.14.
Please retry with newest snapshot or wait for the release.
Download at http://www.minigameslib.de/downloads_en.php
