### ISSUE TITLE
Issue: No Set Main lobby

### ISSUE THREAD

**Issue by EddiesLife247** [MysticCity/MinigamesAPI#201]
When there has been no setmainlobby set for a any minigame plugin the plugin shows the following error when saving arenas:

an unexpected error occured, check the console

Console shows: 

[21:36:52] [Server thread/INFO]: [0;31;1mYou forgot to set the mainlobby![m
[21:36:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'snake' in plugin MGSnake v1.14.14-20170105.215249
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getWorld(CraftServer.java:1023) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at com.comze_instancelabs.minigamesapi.util.Util.getMainLobby(Util.java:302) ~[?:?]
	at com.comze_instancelabs.minigamesapi.util.Util.initArena(Util.java:717) ~[?:?]
	at com.comze_instancelabs.minigamesapi.ArenaSetup.saveArena(ArenaSetup.java:191) ~[?:?]
	at com.comze_instancelabs.minigamesapi.commands.CommandHandler.saveArena(CommandHandler.java:540) ~[?:?]
	at com.comze_instancelabs.minigamesapi.commands.CommandHandler.handleArgs(CommandHandler.java:109) ~[?:?]
	at com.comze_instancelabs.mgsnake.Main.onCommand(Main.java:195) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	... 15 more

the error:
[21:36:52] [Server thread/INFO]: [0;31;1mYou forgot to set the mainlobby![m
is not shown to the admin when saving an arena

**Comment by mepeisen** [comment]
could be a smarter error message

**Comment by mepeisen** [comment]
fixed Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.
