### ISSUE TITLE
Bug Sets the arena to only1 level

### ISSUE THREAD

**Issue by Jacobnordvall** [MysticCity/MinigamesAPI#206]
Instead of using the high and low bounds it only registers the top floor.

Here is the intresting part of the log:

[18:10:31] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MGSplegg v1.14.14-20170105.215322
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:942) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.comze_instancelabs.minigamesapi.ArenaListener.onSignUse(ArenaListener.java:1705) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	... 18 more
[18:10:31] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MGSplegg v1.14.14-20170105.215322
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:942) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.comze_instancelabs.minigamesapi.ArenaListener.onSignUse(ArenaListener.java:1705) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	... 18 more
[18:10:32] [Server thread/INFO]: [MGSplegg] 7 to reset for arena Arena1.
[18:10:32] [Server thread/WARN]: [LagMonitor] Plugin MinigamesLib is performing a blocking action to socket://api.mojang.com:443 on the main thread This could be a performance hit. Report it to the plugin author
[18:10:32] [Server thread/WARN]: [LagMonitor] 
java.lang.Exception
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:40) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_91]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:1.8.0_91]
	at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:77) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:54) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.UserCache.a(UserCache.java:88) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.UserCache.getProfile(UserCache.java:157) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getOfflinePlayer(CraftServer.java:1305) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:731) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftScoreboard.getPlayers(CraftScoreboard.java:148) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftScoreboard.getPlayers(CraftScoreboard.java:1) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at com.comze_instancelabs.minigamesapi.util.ArenaScoreboard.clearScoreboard(ArenaScoreboard.java:285) ~[?:?]
	at com.comze_instancelabs.minigamesapi.Arena.stop(Arena.java:2043) ~[?:?]
	at com.comze_instancelabs.mgsplegg.IArena.stop(IArena.java:157) ~[?:?]
	at com.comze_instancelabs.minigamesapi.Arena.lambda$spectateGame$13(Arena.java:1421) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[18:10:32] [Server thread/INFO]: [MinigamesLib] resetting block Location{world=CraftWorld{name=world},x=5650.0,y=14.0,z=-3130.0,pitch=0.0,yaw=0.0}
[18:10:32] [Server thread/INFO]: [MinigamesLib] resetting block Location{world=CraftWorld{name=world},x=5810.0,y=80.0,z=-3381.0,pitch=0.0,yaw=0.0}
[18:10:32] [Server thread/INFO]: [MinigamesLib] resetting block Location{world=CraftWorld{name=world},x=5812.0,y=81.0,z=-3381.0,pitch=0.0,yaw=0.0}
[18:10:32] [Server thread/INFO]: [MinigamesLib] resetting block Location{world=CraftWorld{name=world},x=5811.0,y=81.0,z=-3380.0,pitch=0.0,yaw=0.0}
[18:10:32] [Server thread/INFO]: [MinigamesLib] resetting block Location{world=CraftWorld{name=world},x=5810.0,y=81.0,z=-3379.0,pitch=0.0,yaw=0.0}
[18:10:32] [Server thread/INFO]: [MinigamesLib] resetting block Location{world=CraftWorld{name=world},x=5811.0,y=81.0,z=-3381.0,pitch=0.0,yaw=0.0}
[18:10:32] [Server thread/INFO]: [MinigamesLib] resetting block Location{world=CraftWorld{name=world},x=5810.0,y=81.0,z=-3380.0,pitch=0.0,yaw=0.0}

**Comment by mepeisen** [comment]
hmmm. I fixed the NullPointerException.
It comes from compass tracking.
Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.

What exactly are you describing? Does the compass only respect 1 level of the arena?
I do not have an idea why your log (which actually represents a bug) depends on the problem you are describing.

**Comment by mepeisen** [comment]
please respond and I will reopen the bug if you have some additional information.
Or maybe your original problem is gone in latest snapshot.
