### ISSUE TITLE
Console error (Causing extreme lag)

### ISSUE THREAD

**Issue by Jacobnordvall** [MysticCity/MinigamesAPI#207]
[20:13:51] [Server thread/WARN]: [LagMonitor] Plugin MGSnake is performing a blocking action to socket://api.mojang.com:443 on the main thread This could be a performance hit. Report it to the plugin author
[20:13:51] [Server thread/WARN]: [LagMonitor] 
java.lang.Exception
at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:40) ~[?:?]
at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_91]
at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:1.8.0_91]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:1.8.0_91]
at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:77) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:54) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at net.minecraft.server.v1_11_R1.UserCache.a(UserCache.java:88) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at net.minecraft.server.v1_11_R1.UserCache.getProfile(UserCache.java:157) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getOfflinePlayer(CraftServer.java:1305) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:731) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at com.comze_instancelabs.mgsnake.IArenaScoreboard.updateScoreboard(IArenaScoreboard.java:56) ~[?:?]
at com.comze_instancelabs.mgsnake.IArenaScoreboard.updateScoreboard(IArenaScoreboard.java:86) ~[?:?]
at com.comze_instancelabs.minigamesapi.Arena.lambda$start$19(Arena.java:1714) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[20:14:24] [Server thread/WARN]: Sallad_Ass moved too quickly! -456.53186717948574,-42.0,101.45383402368816

**Comment by mepeisen** [comment]
thanks for reporting.

**Comment by Owenftw** [comment]
Possible for any performance improvements for survival servers?
https://timings.aikar.co/?id=5bd200eeee494ac9a8c92af081797bbc&section=lag

It looks like it's mostly Splegg and Deathrun that are the highest causes of lag spikes.

**Comment by mepeisen** [comment]
Please check the latest snapshot till next weekend. I fixed lags caused by scoreboard updates. Are there any additional problems and lags?

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.

**Comment by mepeisen** [comment]
*closed* If this does not help please respond. I will reopen the issue.

**Comment by Jacobnordvall** [comment]
it frezes and gives me a log error saying that some of your minigames are
lagging because of .....

2017-02-12 10:37 GMT+01:00 Owenftw <notifications@github.com>:

**Comment by mepeisen** [comment]
Thanks for your report. Before reopening the issue: Are you using the latest stable V1.14.15?

**Comment by Jacobnordvall** [comment]
Its fixed now :)

**Comment by mepeisen** [comment]
thx.
If you experience any further performance problem, even if it is not so bad, please report.
We really want to have a clean, fast and nice plugin ;-)

**Comment by Jacobnordvall** [comment]
Hey,

I just signed the petition "Stoppt die Zensurmaschine – Rettet das
Internet! #Uploadfilter #Artikel13 #SaveYourInternet" and wanted to see if
you could help by adding your name.

Our goal is to reach 6,000,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/ytfCLcWd5X

Thanks!
Jacob
