### ISSUE TITLE
Arenasigns Error

### ISSUE THREAD

**Issue by xXSchrandXx** [MysticCity/MinigamesAPI#210]
I do get an error everytime a player interact with a sign:

> `[20:17:53

 ERROR]: Could not pass event PlayerInteractEvent to MinigamesLib v1.14.14-20170105.211143
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getWorld(CraftServer.java:1022) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.Bukkit.getWorld(Bukkit.java:501) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at com.comze_instancelabs.minigamesapi.MinigamesAPI.getServerBySignLocation(MinigamesAPI.java:1763) ~[?:?]
        at com.comze_instancelabs.minigamesapi.MinigamesAPI.onSignUse(MinigamesAPI.java:1503) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        ... 17 more
`

**Comment by mepeisen** [comment]
woho. World is null.
Did you add the sign manually or did you edit the arenas.yml file by hand?

**Comment by xXSchrandXx** [comment]
I do not have arenas on my Lobby Server
I had the MinigamesLib just for the Server switching

**Comment by mepeisen** [comment]
I reviewed the bug. However I cannot reproduce it. Can you post the config.yml of your lobby server?
Some of your signs contain a world that does not exist on your lobby server.

**Comment by xXSchrandXx** [comment]
`# MinigamesAPI Config #
# If you want bugfree versions, turn this to true:
# NO USE TRUE MODE!
config:
  auto_updating: true
  post_metrics: true
  party_command_enabled: true
  debug: false
  permissions_prefix: ancient.core
  permissions_kits_prefix: ancient.core.kits
  permissions_gun_prefix: ancient.core.guns
  permissions_shop_prefix: ancient.core.shopitems
  permissions_game_prefix: ancient.
  motd:
    enabled: false
    rotation: 15
    text: '<minigame> arena <arena> <state>: <players>/<maxplayers>'
    state:
      join: JOIN
      starting: STARTING
      ingame: INGAME
      restarting: RESTARTING
      disabled: DISABLED
signs_updating_time: 20
signs:
  join:
    '0': '&8[&a&lJOIN&8]'
    '1': '&a<minigame>'
    '2': '&a<count>/<maxcount>'
    '3': '&a'
  starting:
    '0': '&8[&a&lJOIN&8]'
    '1': '&a<minigame>'
    '2': '&a<count>/<maxcount>'
    '3': '&a'
  ingame:
    '0': '&8[&4&lINGAME&8]'
    '1': '&a<minigame>'
    '2': '&b<count> &aSpieler'
    '3': '&a'
  restarting:
    '0': '&8[&c&lNEUSTART&8]'
    '1': '&e<minigame>'
    '2': '&e<count>/<maxcount>'
    '3': '&e'
  spec:
    '0': '&8[&a&lSPECTATE&8]'
    '1': '&a<minigame>'
    '2': '&b<count> &aSpieler'
    '3': '&a'
arenas:
  MGBowBash:
    '1': {}
  MGConquer:
    '1': {}
  MGGungames:
    '1': {}
  MGOneinTheChamber:
    '1': {}
  MGSeaBattle:
    '1': {}
  MGSkyWars:
    '1': {}
  MGDeathrun:
    '1': {}
  MGFlyingCars:
    '1': {}
  MGNoteblockBlitz:
    '1': {}
  MGSnake:
    '1': {}
  MGSplegg&Spleef:
    '1': {}
  MGBedwars:
    '1': {}
  MGDeathRun:
    '1': {}
  MGSplegg:
    '1': {}
  MGGunGames:
    '1': {}
  MGOITC:
    '1': {}
`

**Comment by mepeisen** [comment]
very strange. Did you create join signs? Your config.yml seems to be corrupt. Your arenas section contains an arena called '1' without signs for every minigames.
Please remove everything below arenas: and check if it can be used without errors.

**Comment by mepeisen** [comment]
You will may have to recreate the signs. Successful sign creation should lead to following config:

arenas:
  <minigame>:
    <arenaname>:
      sign:
        server: <target-servername>
        world: <world or sign>
        loc:
          x: <x-coord of sign>
          y: <y-coord of sign>
          z: <z-coord of sign>

**Comment by mepeisen** [comment]
*closed* If this does not help please responde. I will reopen the issue.
If you find out why the config gets corrupt please respond. There may be a bug I do not see at the moment. :-)
