### ISSUE TITLE
MobEscape

### ISSUE THREAD

**Issue by Imp5pa** [MysticCity/MinigamesAPI#228]
If I type /de setspawn TEST, internal error show.
[12:33:59 INFO]: Lemon_CZE issued server command: /de save Arena1
[12:33:59 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'de' in plugin MGMobEscape v1.6.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at com.comze_instancelabs.minigamesapi.util.Util.getMainLobby(Util.java:297) ~[?:?]
	at com.comze_instancelabs.minigamesapi.commands.CommandHandler.saveArena(CommandHandler.java:540) ~[?:?]
	at com.comze_instancelabs.minigamesapi.commands.CommandHandler.handleArgs(CommandHandler.java:109) ~[?:?]
	at com.comze_instancelabs.mgmobescape.Main.onCommand(Main.java:194) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	... 15 more
Please fix, Iam using 1.11.2

**Comment by mepeisen** [comment]
Which minigames version are you using? Is this the first exception you get or are there more errors while starting the server?

**Comment by mepeisen** [comment]
closed because of no Response.
If you still having the issue please respond and I will reopen the issue.
