### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CrafttJ** [MysticCity/MinigamesAPI#243]
**Since I have got this plugin, I get spammed with this error:**

[16:26:39 ERROR]: Could not pass event CreatureSpawnEvent to MGOITC v1.14.15-20170305.080528
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:280) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.World.addEntity(World.java:977) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.WorldServer.addEntity(WorldServer.java:1079) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.SpawnerCreature.a(SpawnerCreature.java:293) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.ChunkProviderGenerate.recreateStructures(ChunkProviderGenerate.java:378) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.craftbukkit.v1_10_R1.generator.NormalChunkGenerator.recreateStructures(NormalChunkGenerator.java:41) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.Chunk.a(Chunk.java:964) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.Chunk.loadNearby(Chunk.java:935) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.comze_instancelabs.minigamesapi.util.Cuboid.containsLoc(Cuboid.java:91) ~[?:?]
        at com.comze_instancelabs.minigamesapi.ArenaListener.onMobSpawn(ArenaListener.java:2130) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-850da7e-b6490da]
        ... 21 more

**Comment by mepeisen** [comment]
thats strange. However the code is a check to prevent mob spawns inside arenas. So that players are not influenced and hunted by world monsters.
The NullPointerException is raised because the Spawn location (the world) is null.

Are you using multiple worlds? MultiVerse? Any special plugins influencing the monsters?

I fixed the error actually but it would be nice to get the reason this is happening.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.
