### ISSUE TITLE
Leave sign -> NullPointerException

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#26]
Spigot 1.10 latest pull, with standard up-to-date plugins: WE/WG, MV, PEX, and now MG, pulls from github 1.14.9-20160620.02xxxx. In both FC and SC, the following when clicking on "Leave" sign (which does leave the arena):

[15:41:45 ERROR]: Could not pass event PlayerInteractEvent to MGSnake v1.3.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at com.comze_instancelabs.minigamesapi.util.Util.updateSign(Util.java:426) ~[?:?]
        at com.comze_instancelabs.minigamesapi.ArenaListener.onSignUse(ArenaListener.java:848) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar-2016-06-20-0007:git-Spigot-c55900f-9af379f]

**Comment by mepeisen** [comment]
please reopen if my temporary fix does not work.

**Comment by SlimeDog** [comment]
Fix seems to work. No repeats of cited console error.
