### ISSUE TITLE
Fehlermeldung MinigamesLib und HorseRacing

### ISSUE THREAD

**Issue by maybeto** [MysticCity/MinigamesAPI#273]
hi, ich bekomme folgende Fehlermeldungen nach der Installation von MinigamesLib und Horseracing.
Der Server läuft auf Version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)

[23:04:12] [Server thread/WARN]: [MinigamesLib] exception
java.io.IOException: Datei oder Verzeichnis nicht gefunden
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_131]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_131]
	at com.comze_instancelabs.horseracingplus.ArenaSystem.logMessage(ArenaSystem.java:114) [MGHorseRacingPlus-Plugin-1.14.16.jar:?]
	at com.comze_instancelabs.horseracingplus.Main.onSignUse(Main.java:1103) [MGHorseRacingPlus-Plugin-1.14.16.jar:?]
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[23:04:23] [Server thread/WARN]: [MGHorseRacingPlus] Task #12847 for MGHorseRacingPlus v1.14.16-20170514.150257 generated an exception
java.lang.NoSuchFieldError: ENTITY_CAT_AMBIENT
	at com.comze_instancelabs.horseracingplus.ArenaSystem.countdownfunc(ArenaSystem.java:181) ~[?:?]
	at com.comze_instancelabs.horseracingplus.Main$13.run(Main.java:1110) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[23:05:01] [Server thread/INFO]: [0;36;22miCheshireCat won a HorseRace![m
[23:05:19] [Server thread/WARN]: [MGHorseRacingPlus] Task #14766 for MGHorseRacingPlus v1.14.16-20170514.150257 generated an exception
java.lang.NoSuchFieldError: ENTITY_CAT_AMBIENT
	at com.comze_instancelabs.horseracingplus.ArenaSystem.countdownfunc(ArenaSystem.java:181) ~[?:?]
	at com.comze_instancelabs.horseracingplus.Main$13.run(Main.java:1110) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by mepeisen** [comment]
Ich habe das Log mal aufs Wesentliche gekürzt :-)
Das Fehler-Spamming solltest du kurzfristig wegbekommen, wenn du mal manuell das Verzeichnis "plugins/HorseRacingPlus" erstellst.
Sollte dieses Wochenende Zeit haben, den Fehler zu korrigieren.

**Comment by maybeto** [comment]
Hi,
habe das Verzeichnis erstellt, was die Fehlermeldung auf folgendes reduziert hat

[11:26:47] [Server thread/WARN]: [MGHorseRacingPlus] Task #40705 for MGHorseRacingPlus v1.14.16-20170514.150257 generated an exception
java.lang.NoSuchFieldError: ENTITY_CAT_AMBIENT
	at com.comze_instancelabs.horseracingplus.ArenaSystem.countdownfunc(ArenaSystem.java:181) ~[?:?]
	at com.comze_instancelabs.horseracingplus.Main$13.run(Main.java:1110) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by mepeisen** [comment]
fixed

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
