### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by xbxymax** [MysticCity/MinigamesAPI#281]
MGDeathRun
Regardless of how I set it, he kept the data in stat.yml
I tested other small games and all of them had the same problem

mysql:
enabled: true
host: 127.0.0.1
user: root
pw: xxx
database: mcminigames

[17:57:00 WARN]: [MinigamesLib] exception
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''player', 'points', 'wins', 'loses', 'kills', 'deaths', 'uuid', 'gamepoints') VA' at line 1
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595) ~[j15spleef.jar:git-Paper-1104]
at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468) ~[j15spleef.jar:git-Paper-1104]
at com.comze_instancelabs.minigamesapi.sql.MainSQL.updateLosterStats(MainSQL.java:306) ~[?:?]
at com.comze_instancelabs.minigamesapi.sql.MainSQL.updateLoserStats(MainSQL.java:270) ~[?:?]
at com.comze_instancelabs.minigamesapi.Stats.lose(Stats.java:95) ~[?:?]
at com.comze_instancelabs.minigamesapi.Rewards.giveWinReward(Rewards.java:384) ~[?:?]
at com.comze_instancelabs.minigamesapi.Arena.lambda$leavePlayerRaw$13(Arena.java:1347) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [j15spleef.jar:git-Paper-1104]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [j15spleef.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [j15spleef.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [j15spleef.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [j15spleef.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [j15spleef.jar:git-Paper-1104]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by TheUser816** [comment]
Try removing your existing tables in the database and restart the server.
Check for further errors.

**Comment by xbxymax** [comment]
No matter how I try, at the end of the game will appear this error
I even use the latest build version or have this problem
I also tried to create their own data sheet is not OK

		mysql update "CREATE TABLE IF NOT EXISTS `MGDeathRun` (`id` varchar(255),`player` longtext,`points` longtext,`wins` longtext,`loses` longtext,`kills` longtext,`deaths` longtext,`uuid` longtext,`gamepoints` longtext)"
		mysql update "ALTER TABLE `MGDeathRun` ADD PRIMARY KEY (id)"

[00:57:36 WARN]: [MinigamesLib] exception
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''player', 'points', 'wins', 'loses', 'kills', 'deaths', 'uuid', 'gamepoints') VA' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468) ~[j15spleef.jar:git-Paper-1104]
        at com.comze_instancelabs.minigamesapi.sql.MainSQL.updateLosterStats(MainSQL.java:306) ~[?:?]
        at com.comze_instancelabs.minigamesapi.sql.MainSQL.updateLoserStats(MainSQL.java:270) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Stats.lose(Stats.java:95) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Rewards.giveWinReward(Rewards.java:384) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Arena.lambda$leavePlayerRaw$13(Arena.java:1347) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [j15spleef.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [j15spleef.jar:git-Paper-1104]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by TheUser816** [comment]
I can **confirm** this happening with MYSQL and MinigamesLib version 1.14.18 (DevBuild) and also  1.14.17

The same error is being displayed.

**Comment by mepeisen** [comment]
should be fixed now

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
