### ISSUE TITLE
null

### ISSUE THREAD

**Issue by Marcell0101** [MysticCity/MinigamesAPI#287]
This is only happening on my server, but I really want to fix it.

[21:10:40 ERROR]: null org.bukkit.command.CommandException: Unhandled exception executing command 'nb' in plugin MGNoteblockBlitz v1.14.17-20170612.054543
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: com.comze_instancelabs.minigamesapi.MinigamesAPI.getPermissionGamePrefix(Ljava/lang/String;)Ljava/lang/String;
        at com.comze_instancelabs.noteblockblitz.Main.onCommand(Main.java:146) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
        ... 15 more
 
Pls respond soon!

**Comment by mepeisen** [comment]
Which version of MinigamesLib do you use?
Seems that you are using incompatible versions

**Comment by Marcell0101** [comment]
I am using 1.13.1 and my server is running 1.9 spigot.

Btw thanks for the fast reply!

**Comment by mepeisen** [comment]
This does not work. The jars are incompatible.
Please upgrade MinigamesLib to 1.14.17 (same version number as your minigame plugin).

**Comment by Marcell0101** [comment]
Ok thanks, It worked.
