### ISSUE TITLE
CraftBlockState cannot be cast to org.bukkit.block.Sign

### ISSUE THREAD

**Issue by prodigyrick** [MysticCity/MinigamesAPI#288]
this is continues every 1 second.
Running mgsplegg.

[23:40:09 WARN]: [MinigamesLib] Task #43 for MinigamesLib v1.14.17-20170612.052814 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
        at com.comze_instancelabs.minigamesapi.LobbySignManager$SignData.setSignData(LobbySignManager.java:276) ~[?:?]
        at com.comze_instancelabs.minigamesapi.LobbySignManager.ping(LobbySignManager.java:307) ~[?:?]
        at com.comze_instancelabs.minigamesapi.MinigamesAPI.lambda$onEnable$6(MinigamesAPI.java:435) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[23:40:10 WARN]: [MinigamesLib] Task #43 for MinigamesLib v1.14.17-20170612.052814 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
        at com.comze_instancelabs.minigamesapi.LobbySignManager$SignData.setSignData(LobbySignManager.java:276) ~[?:?]
        at com.comze_instancelabs.minigamesapi.LobbySignManager.ping(LobbySignManager.java:307) ~[?:?]
        at com.comze_instancelabs.minigamesapi.MinigamesAPI.lambda$onEnable$6(MinigamesAPI.java:435) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by mepeisen** [comment]
Did you remove signs while plugin was disabled?

**Comment by prodigyrick** [comment]
neither splegg nor the lib have been disabled.

**Comment by prodigyrick** [comment]
so for 10 hours 57 mins its been doing the same thing. Any suggestions?

**Comment by mepeisen** [comment]
please use the latest snapshot.
Now there should be a log warning every 30 seconds like:
- Cannot find lobby sign for <minigame>/<arena> at position <pos>
This should clear up what is broken. 

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

**Comment by prodigyrick** [comment]
Im confused as to which download to take. I got the older 1.4.18 from 7-16 packaged, but its still older than this date you say is suppose to be the latest snapshot. I see no 30 second warning, so I clearly have the wrong download.

**Comment by mepeisen** [comment]
oops :-(
Did not see that the hudson build was failing. http://hudson.xworlds.eu/job/MinigamesLib/84/

I started a new build with skipping javadoc. As soon as it is finished there will be a newer version.
http://hudson.xworlds.eu/job/MinigamesLib/85/
For the complete package you should wait a while.

**Comment by prodigyrick** [comment]
the lib is good for me for now.

**Comment by prodigyrick** [comment]
That got it. Thank you.

**Comment by mepeisen** [comment]
ok. You may take the warning and look at the mentioned block. Simply re-create the lobby sign there to fix it at all.

I am closing the bug now. thx for reporting ;-)

**Comment by prodigyrick** [comment]
Ok I remember having started to place signs there at one time, but they are removed. How do I fix the error?
