### ISSUE TITLE
Bedwars Disabled! Error

### ISSUE THREAD

**Issue by ThePolishThomas** [MysticCity/MinigamesAPI#296]
Hi, I have a problem. After installing the MGbedwars plugin I have some errors. Plugin not working :(
Error - logs:
```
[15:15:15] [Server thread/INFO]: [MinigamesLib] Â§cÂ§lLoaded MinigamesAPI. We're on V1_11_R1.
[15:15:15] [Server thread/INFO]: [MGSkyWars] Enabling MGSkyWars v1.14.17-20170612.054656
[15:15:15] [Server thread/INFO]: [MGBedWars] Enabling MGBedWars v1.14.17-20170612.053900
[15:15:15] [Server thread/ERROR]: Error occurred while enabling MGBedWars v1.14.17-20170612.053900 (Is it up to date?)
java.lang.NullPointerException
	at net.minecraft.server.v1_11_R1.EntityVillager$1.a(EntityVillager.java:194) ~[mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DataConverterManager.c(SourceFile:62) ~[mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DataConverterManager.a(SourceFile:40) ~[mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DataInspectorEntity.a(SourceFile:41) ~[mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DataConverterManager.c(SourceFile:62) ~[mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DataConverterManager.a(SourceFile:40) ~[mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DataConverterManager.a(SourceFile:33) ~[mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.ItemStack.convertStack(ItemStack.java:88) ~[mg.jar:git-Paper-1101]
	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:49) ~[mg.jar:git-Paper-1101]
	at com.comze_instancelabs.bedwars.villager.OBCCraftItemStack111.asNMSCopy(OBCCraftItemStack111.java:13) ~[?:?]
	at com.comze_instancelabs.bedwars.villager.MerchantOffer111.getHandle(MerchantOffer111.java:29) ~[?:?]
	at com.comze_instancelabs.bedwars.villager.Merchant111.addOffer(Merchant111.java:87) ~[?:?]
	at com.comze_instancelabs.bedwars.villager.Merchant111.addOffer(Merchant111.java:52) ~[?:?]
	at com.comze_instancelabs.bedwars.Main.loadTrades(Main.java:289) ~[?:?]
	at com.comze_instancelabs.bedwars.Main.onEnable(Main.java:184) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[mg.jar:git-Paper-1101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [mg.jar:git-Paper-1101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [mg.jar:git-Paper-1101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [mg.jar:git-Paper-1101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [mg.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [mg.jar:git-Paper-1101]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[15:15:15] [Server thread/INFO]: [MGBedWars] Disabling MGBedWars v1.14.17-20170612.053900
[15:15:15] [Server thread/INFO]: [MGDeathRun] Enabling MGDeathRun v1.14.17-20170612.054203
[15:15:15] [Server thread/INFO]: [MGBowBash] Enabling MGBowBash v1.14.17-20170612.054041
[15:15:15] [Server thread/INFO]: Done (11.457s)! For help, type "help" or "?"
```
Thank you for all the responses :)

**Comment by mepeisen** [comment]
This is a fresh install? Did you edit gui.yml?

**Comment by ThePolishThomas** [comment]
Heeelp

**Comment by ThePolishThomas** [comment]
Heeelp

**Comment by mepeisen** [comment]
Answer the questions and stop spamming

**Comment by ThePolishThomas** [comment]
Yes, this os fresh install.

**Comment by mepeisen** [comment]
Anyhow. As long as you do not answer the questions I cannot help. Sorry.
I don't know your setup. I don't know if you edited files manually and did some mistake.
If you send me the files I will reopen.
