### ISSUE TITLE
MGSkyWars Classes

### ISSUE THREAD

**Issue by Jincher** [MysticCity/MinigamesAPI#298]
Hi 

I cant set the deafault class to false. After server reload it will come back again and i have to reupload the config and reload Skywars for.

and we run a Minecraft 1.8.8 server where this comes up in the console:

>[14:03:14] [Server thread/INFO]: [MinigamesLib] Enabling MinigamesLib v1.14.17-20170612.052814
[14:03:14] [Server thread/INFO]: [MinigamesLib] §c§lLoaded MinigamesAPI. We're on V1_8_R3.
[14:03:14] [Server thread/INFO]: [MGSkyWars] Enabling MGSkyWars v1.14.17-20170612.054656
[14:03:14] [Server thread/WARN]: [MinigamesLib] Failed to load class items
java.lang.NumberFormatException: For input string: "64e"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_131]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_131]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_131]
	at com.comze_instancelabs.mgskywars.Main.parseItems(Main.java:395) [MGSkyWars-Plugin-1.14.17.jar:?]
	at com.comze_instancelabs.mgskywars.Main.onEnable(Main.java:101) [MGSkyWars-Plugin-1.14.17.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by mepeisen** [comment]
can you paste/link your classes.yml?

**Comment by mepeisen** [comment]
Sry for late answer. Had some private things to do.
The console error is caused by a corrupt chests.yml. Maybe the plugin gets confused because of the unexpected runtime exception.
So please fix this error in chests.yml first and have a look if the other problem with classes.yml still exists.
