### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fyrlex** [MysticCity/MinigamesAPI#326]
[17:24:24 WARN]: [MinigamesLib] Unable to check plugin version
java.io.IOException: Server returned HTTP response code: 503 for URL: http://nexus.xworlds.eu/minigames/query?group=com.github.MCE-Plugins&artifact=MinigamesLib&version=1.14.17&server=v1_8_R3
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_112]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_112]
        at com.comze_instancelabs.minigamesapi.util.UpdaterNexus.run(UpdaterNexus.java:103) [MinigamesLib-1.14.17.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by mepeisen** [comment]
I moved some things to new servers. You got it during downtime. Should be fixed know.

*closed* If this does not help please respond. I will reopen the issue.
