### ISSUE TITLE
GMobEscape-Plugin not working, Minecraft 1.10

### ISSUE THREAD

**Issue by sajmonyyek** [MysticCity/MinigamesAPI#332]
Hi,

I installed https://www.spigotmc.org/resources/minigameslib.23844/ and https://www.spigotmc.org/resources/mobescape.23851/

I got error like this:

Could not load 'plugins/MGMobEscape-Plugin-1.14.17.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MinigamesLib
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

**Comment by sajmonyyek** [comment]
[01:27:21 ERROR]: Could not load 'plugins/MinigamesLib-1.14.17.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/comze_instancelabs/minigamesapi/MinigamesAPI : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:275) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.UnsupportedClassVersionError: com/comze_instancelabs/minigamesapi/MinigamesAPI : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_80]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	... 6 more

**Comment by sajmonyyek** [comment]
FIXED.
