### ISSUE TITLE
MGskywars error in console 

### ISSUE THREAD

**Issue by yzandre** [MysticCity/MinigamesAPI#53]
i have this problem when i am in another world :

serveur: spigot 1.9.4
Minigameslib: 1.14.8
MGSkywars: 1.5.3

`[Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to MGSkyWars v1.5.3
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1531) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
at com.comze_instancelabs.minigamesapi.ArenaListener.NoClickEntityInLobby(ArenaListener.java:371) ~[?:?]
at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
... 15 more`

**Comment by mepeisen** [comment]
Can you check the latest snapshot?
http://nexus.xworlds.eu:8080/nexus/content/groups/mce/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/

**Comment by yzandre** [comment]
thank you the snapshot resolved my error :)
