### ISSUE TITLE
Minigameslib plugin, and gungame and other minigames of MysticCity don't work on 1.8.8!

### ISSUE THREAD

**Issue by TheKingCreepy** [MysticCity/MinigamesAPI#98]
Hey, minigames lib, gungame and skywars dont work on spigot 1.8.8 server. (Latest version)
HELP!

**Comment by mepeisen** [comment]
What versions are you using?
What exactly is the problem?
Any error in console?

**Comment by TheKingCreepy** [comment]
Version: 1.14.10
Problem is im upload a MGSkyWars-Plugin-1.14.10, MGGunGame-Plugin-1.14.10 and MinigamesLib-1.14.10.jar
And dont work nothing.
Error:
[19:38:26 ERROR]: Could not load 'plugins/MinigamesLib-1.14.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/comze_instancelabs/minigamesapi/MinigamesAPI : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:275) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: java.lang.UnsupportedClassVersionError: com/comze_instancelabs/minigamesapi/MinigamesAPI : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
        at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_80]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        ... 6 more
[19:38:26 ERROR]: Could not load 'plugins/MGGunGame-Plugin-1.14.10.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MinigamesLib
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
[19:38:26 ERROR]: Could not load 'plugins/MGSkyWars-Plugin-1.14.10 (1).jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MinigamesLib
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Server version: 1.8.8

**Comment by mepeisen** [comment]
you need java 1.8.
Please upgrade.

**Comment by TheKingCreepy** [comment]
haha thanks :D
p.s Best skywars plugin

**Comment by mepeisen** [comment]
Please send us a notification if it works.
And please upgrade your review at spigot.
We will add information on apigot and github that it requires Java 1.8

**Comment by TheKingCreepy** [comment]
Yes, it work.

**Comment by mepeisen** [comment]
thx

**Comment by TheKingCreepy** [comment]
One problem :/
I save arena it say: 
An internal error occurred while attempting to perform this command

**Comment by TheKingCreepy** [comment]
I fix, sorry xD

**Comment by TheKingCreepy** [comment]
Agin problem :( When i create sigin:
IGunGameI
IGG-1       I
I                I  This sigin, it created and i can join sigin. 
I               I

**Comment by mepeisen** [comment]
The join changes it color? It detect you want a join sign?
Any errors in console?

Does the Chat command to join work?

**Comment by mepeisen** [comment]
As you can see in #100 it actually misses the support for server version 1.8.8/1.8.9
will be fixed in the next hours

**Comment by mepeisen** [comment]
please retry with latest snapshot http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.11-SNAPSHOT/Minigames-All-1.14.11-20160817.071937-5-bin.zip

**Comment by mepeisen** [comment]
closing this issue.
If there are still problems please write a new comment.
